sudo: required

services:
  - docker

before_install:
  - docker build -t induktor/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run induktor/react-test npm test -- --coverage

after_success:
  - docker build -t induktor/multi-client ./client
  - docker build -t induktor/multi-nginx ./nginx
  - docker build -t induktor/multi-server ./server
  - docker build -t induktor/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push induktor/multi-client
  - docker push induktor/multi-nginx
  - docker push induktor/multi-server
  - docker push induktor/multi-worker